### ISSUE TITLE
Docker compose mounting issue

### ISSUE THREAD

**Issue by swamp-agr** [FinleyMcIlwaine/eventlog-live-infra#2]
As macOS user I have tried to follow your advice on bringing up app in the image and compose it up with the rest setup.

For `example` app I have introduced following `Dockerfile`:

```
FROM haskell:9.4

USER "root"

COPY --chown=${USER} cabal.project example.cabal Main.hs ./

RUN cabal update

RUN cabal build --allow-newer

RUN cabal install --overwrite-policy=always --allow-newer

CMD ["example"]
```

Build it as `docker build -t example-app .`, add to `docker-compose.yml` like that:

```
  example-app:
    image: example-app
    restart: "always"
    environment:
      GHC_EVENTLOG_SOCKET: "/tmp/ghc-eventlog-socket"
    volumes:
    - "${GHC_EVENTLOG_SOCKET:-/tmp/ghc-eventlog-socket}:/tmp/ghc-eventlog-socket"
    command: "example -- +RTS -l -hT --eventlog-flush-interval=1"
```

And add dependency for influxdb:

```
  influxdb:
    image: "influxdb:1.8"
    restart: "always"
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "eventlog"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
    depends_on:
      example-app:
        condition: "service_started"
  influxdb:
    image: "influxdb:1.8"
    restart: "always"
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "eventlog"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
    # following lines have been added: 
    depends_on: 
      example-app:
        condition: "service_started"
```

And tried to run it all-at-once. 

And now Docker is confused. If I understand correctly, the `example-app` needs a socket as file but influxdb tried to consume it as a directory.

```
[+] Running 4/4
 ✔ Container eventlog-live-infra-example-app-1    Created                                                                                                                                              0.0s
 ✔ Container eventlog-live-infra-grafana-1        Running                                                                                                                                              0.0s
 ✔ Container eventlog-live-infra-influxdb-1       Created                                                                                                                                              0.0s
 ✔ Container eventlog-live-infra-eventlog-live-1  Created                                                                                                                                              0.0s
Attaching to eventlog-live-1, example-app-1, grafana-1, influxdb-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/socket_mnt/private/tmp/ghc-eventlog-socket" to rootfs at "/tmp/ghc-eventlog-socket": create mountpoint for /tmp/ghc-eventlog-socket mount: cannot create subdirectories in "/var/lib/docker/rootfs/overlayfs/8f61f856e937ea72092cfbbf6c8c8b9146e8742f01019763baf5b9a67f18b81d/tmp/ghc-eventlog-socket": not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Could you please help me understand how to approach the problem?
